# The api key, secret key, and canvas page name are required to get started
# Tunnel configuration is only needed if you are going to use the facebooker:tunnel Rake tasks
# Your callback url in Facebook should be set to http://public_host:public_port
# If you're building a Facebook connect site, 
#    change the value of set_asset_host_to_callback_url to false
# To develop for the new profile design, add the following key..
# api: new
# remove the key or set it to anything else to use the old facebook design.
# This should only be necessary until the final version of the new profile is released.


development:
  api_key: b33d27141426c0ba61e5327b8137db0b
  secret_key: 1de354c13159cd3a0a89b464c7504518
  canvas_page_name: definitious
  callback_url: http://definitious.heroku.com:8888/
  pretty_errors: true
  set_asset_host_to_callback_url: true
  tunnel:
    public_host_username: username
    public_host: definitious.heroku.com
    public_port: 8888
    local_port: 3000
    server_alive_interval: 0

test:
  api_key: b33d27141426c0ba61e5327b8137db0b
  secret_key: 1de354c13159cd3a0a89b464c7504518
  canvas_page_name: definitious
  callback_url: http://definitious.heroku.com:8888/
  pretty_errors: true
  set_asset_host_to_callback_url: true
  tunnel:
    public_host_username: username
    public_host: definitious.heroku.com
    public_port: 8888
    local_port: 3000
    server_alive_interval: 0

production:
  api_key: b33d27141426c0ba61e5327b8137db0b
  secret_key: 1de354c13159cd3a0a89b464c7504518
  canvas_page_name: definitious
  callback_url: http://definitious.heroku.com:8888/
  pretty_errors: true
  set_asset_host_to_callback_url: true
  tunnel:
    public_host_username: username
    public_host: definitious.heroku.com
    public_port: 8888
    local_port: 3000
    server_alive_interval: 0